import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {_Sidebar} from "@/src/widgets/partial/_Sidebar";
import {TaskProvider} from "@/src/features/Context/LessonContext";
import {AuthProvider} from "@/src/features/Context/AuthContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <AuthProvider>
          <TaskProvider>
              <div>
                  {children}
              </div>
          </TaskProvider>
      </AuthProvider>


      </body>
    </html>
  );
}
